In [2]:
import pandas as pd
import numpy as np

In [100]:
pd.Series(np.array([1,2,3,4,5]),index=[1,1,1,1,1])

1    1
1    2
1    3
1    4
1    5
dtype: int64

In [16]:
data1={
    'name': ['Alice Smith', 'Bob Jones', 'Charlie Brown'],
    'age':[12,15,11],
    'class': ['9th Grade', '10th Grade', '9th Grade']
}
f1=pd.DataFrame(data1)
data2=[
    ['Alice Smith',12,'9th Grade'],['Bob Jones',15,'10th Grade'],['Charlie Brown',11,'9th Grade']]
f2=pd.DataFrame(data2,columns=['name','age','class'])
f2

            name  age       class
0    Alice Smith   12   9th Grade
1      Bob Jones   15  10th Grade
2  Charlie Brown   11   9th Grade

In [37]:
a=f2[['name','age']]
f2['marks']=[56,34,76]
f2.drop("marks",axis=1)
f2.drop(0,axis=0)

            name  age       class  marks
1      Bob Jones   15  10th Grade     34
2  Charlie Brown   11   9th Grade     76

In [41]:
# select row

f2.loc[0]
f2.iloc[1] #spectfic label

name      Bob Jones
age              15
class    10th Grade
marks            34
Name: 1, dtype: object

In [44]:
f2[f2['age']>11]

            name  age      class  marks
2  Charlie Brown   11  9th Grade     76

In [48]:
f2[(f2['age']>11) & (f2['name']=='Bob Jones')]

        name  age       class  marks
1  Bob Jones   15  10th Grade     34

In [62]:
data = {
    "A": [np.nan, 2, 3, 4, 5],
    "B": [2, np.nan, 4, np.nan, 6],
    "C": [2, 3, 4, np.nan, 6],
    "D": [1, 6, 1, 56, 7],
}
frame=pd.DataFrame(data)
frame

     A    B    C   D
0  NaN  2.0  2.0   1
1  2.0  NaN  3.0   6
2  3.0  4.0  4.0   1
3  4.0  NaN  NaN  56
4  5.0  6.0  6.0   7

In [63]:
frame.isna().sum()

A    1
B    2
C    1
D    0
dtype: int64

In [76]:
frame.dropna(thresh=0)

     A    B    C   D
0  NaN  2.0  2.0   1
1  2.0  NaN  3.0   6
2  3.0  4.0  4.0   1
3  4.0  NaN  NaN  56
4  5.0  6.0  6.0   7

In [77]:
frame.fillna(0)

     A    B    C   D
0  0.0  2.0  2.0   1
1  2.0  0.0  3.0   6
2  3.0  4.0  4.0   1
3  4.0  0.0  0.0  56
4  5.0  6.0  6.0   7

In [96]:
employees_data = {
    'Employee_ID': [101, 102, 103, 104, 105 ,106],
    'Name': ['Sophia', 'Liam', 'Mia', 'Noah', 'Emma',"Rod"],
    'Department': ['HR', 'Engineering', 'Marketing', 'Engineering', 'HR',"PR"],
    'Status': ['Full-Time', 'Full-Time', 'Contract', 'Full-Time', 'Contract',"CEO"]
}
sales_data = {
     'Employee_ID': [101, 102, 103, 104, 105],
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
    'Revenue': [45000, 52000, 49000, 61000, 58000],
    'Expenses': [31000, 32500, 30000, 35000, 33000],
    'Online_Orders': [1200, 1450, 1300, 1900, 1750]
}

In [97]:
df1=pd.DataFrame(employees_data)
df2=pd.DataFrame(sales_data)
df2

   Employee_ID Month  Revenue  Expenses  Online_Orders
0          101   Jan    45000     31000           1200
1          102   Feb    52000     32500           1450
2          103   Mar    49000     30000           1300
3          104   Apr    61000     35000           1900
4          105   May    58000     33000           1750

In [99]:
pd.merge(df1,df2,how="inner")

,Employee_ID,Name,Department,Status,Month,Revenue,Expenses,Online_Orders
0,101,Sophia,HR,Full-Time,Jan,45000,31000,1200
1,102,Liam,Engineering,Full-Time,Feb,52000,32500,1450
2,103,Mia,Marketing,Contract,Mar,49000,30000,1300
3,104,Noah,Engineering,Full-Time,Apr,61000,35000,1900
4,105,Emma,HR,Contract,May,58000,33000,1750

In [98]:
pd.merge(df1,df2,how="outer",on="Employee_ID")

,Employee_ID,Name,Department,Status,Month,Revenue,Expenses,Online_Orders
0,101,Sophia,HR,Full-Time,Jan,45000.0,31000.0,1200.0
1,102,Liam,Engineering,Full-Time,Feb,52000.0,32500.0,1450.0
2,103,Mia,Marketing,Contract,Mar,49000.0,30000.0,1300.0
3,104,Noah,Engineering,Full-Time,Apr,61000.0,35000.0,1900.0
4,105,Emma,HR,Contract,May,58000.0,33000.0,1750.0
5,106,Rod,PR,CEO,NaN,NaN,NaN,NaN

In [102]:
pd.merge(df1,df2,how="right",on="Employee_ID")

,Employee_ID,Name,Department,Status,Month,Revenue,Expenses,Online_Orders
0,101,Sophia,HR,Full-Time,Jan,45000,31000,1200
1,102,Liam,Engineering,Full-Time,Feb,52000,32500,1450
2,103,Mia,Marketing,Contract,Mar,49000,30000,1300
3,104,Noah,Engineering,Full-Time,Apr,61000,35000,1900
4,105,Emma,HR,Contract,May,58000,33000,1750

In [104]:
pd.concat([df1,df2],axis=1)

,Employee_ID,Name,Department,Status,Employee_ID,Month,Revenue,Expenses,Online_Orders
0,101,Sophia,HR,Full-Time,101.0,Jan,45000.0,31000.0,1200.0
1,102,Liam,Engineering,Full-Time,102.0,Feb,52000.0,32500.0,1450.0
2,103,Mia,Marketing,Contract,103.0,Mar,49000.0,30000.0,1300.0
3,104,Noah,Engineering,Full-Time,104.0,Apr,61000.0,35000.0,1900.0
4,105,Emma,HR,Contract,105.0,May,58000.0,33000.0,1750.0
5,106,Rod,PR,CEO,NaN,NaN,NaN,NaN,NaN

In [ ]:
df2.join(df1)

In [113]:
data = {
    'Region': ['East', 'West', 'East', 'North', 'West', 'North', 'East', 'West', 'North', 'South'],
    'Manager': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob', 'Charlie', 'Alice', 'David', 'Charlie', 'David'],
    'Category': ['Electronics', 'Furniture', 'Clothing', 'Electronics', 'Clothing', 'Furniture', 'Furniture', 'Electronics', 'Clothing', 'Electronics'],
    'Sales': [12000, 22000, 8500, 15000, 9200, 18500, 11000, 26000, 7400, 19000],
    'Quantity': [15, 30, 45, 20, 25, 18, 12, 35, 40, 22]
}

df=pd.DataFrame(data)
df

  Region  Manager     Category  Sales  Quantity
0   East    Alice  Electronics  12000        15
1   West      Bob    Furniture  22000        30
2   East    Alice     Clothing   8500        45
3  North  Charlie  Electronics  15000        20
4   West      Bob     Clothing   9200        25
5  North  Charlie    Furniture  18500        18
6   East    Alice    Furniture  11000        12
7   West    David  Electronics  26000        35
8  North  Charlie     Clothing   7400        40
9  South    David  Electronics  19000        22

In [121]:
df.groupby("Region")["Sales"].sum()

Region
East     31500
North    40900
South    19000
West     57200
Name: Sales, dtype: int64

In [128]:
df.groupby(["Region","Category"])["Sales"].sum()

Region  Category
East    Clothing        8500
        Electronics    12000
        Furniture      11000
North   Clothing        7400
        Electronics    15000
        Furniture      18500
South   Electronics    19000
West    Clothing        9200
        Electronics    26000
        Furniture      22000
Name: Sales, dtype: int64

In [131]:
df["Sales"].agg(["mean",'max','min'])

mean    14860.0
max     26000.0
min      7400.0
Name: Sales, dtype: float64

In [136]:
pd.pivot_table(df,values="Sales",index="Region",columns="Category")

Category  Clothing  Electronics  Furniture
Region
East        8500.0      12000.0    11000.0
North       7400.0      15000.0    18500.0
South          NaN      19000.0        NaN
West        9200.0      26000.0    22000.0

In [138]:
pd.crosstab(df["Region"],df['Sales'])

Sales   7400   8500   9200   11000  12000  15000  18500  19000  22000  26000
Region
East        0      1      0      1      1      0      0      0      0      0
North       1      0      0      0      0      1      1      0      0      0
South       0      0      0      0      0      0      0      1      0      0
West        0      0      1      0      0      0      0      0      1      1

In [140]:
# Operations
frame=pd.DataFrame({
    'A':[1,22,3,4,5],
    'B':[61,3,2,4,2],
    'C':[1,21,32,44,2],
    'D':[14,21,3,45,52],
    'E':[1,2,3,4,53]
})
frame

    A   B   C   D   E
0   1  61   1  14   1
1  22   3  21  21   2
2   3   2  32   3   3
3   4   4  44  45   4
4   5   2   2  52  53

In [148]:
frame.shape
frame.size
frame.columns
frame.info()
frame.describe()
frame+10

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
 3   D       5 non-null      int64
 4   E       5 non-null      int64
dtypes: int64(5)
memory usage: 332.0 bytes

    A   B   C   D   E
0  11  71  11  24  11
1  32  13  31  31  12
2  13  12  42  13  13
3  14  14  54  55  14
4  15  12  12  62  63

In [158]:
def sq(x):
    return x*10
frame['A'].apply(sq)

0         10
1    2342560
2        810
3       2560
4       6250
Name: A, dtype: int64